#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
#
# Authors: Isaac Bythewood
# Updated: September 4th, 2014
# -----------------------------------------------------------------------------


if [ ! -f /data/minecraft_server.jar ]
then
    curl "https://s3.amazonaws.com/Minecraft.Download/versions/1.8/minecraft_server.1.8.jar" -o /data/minecraft_server.jar
fi

if ( ! -f /data/eula.txt); then
    echo "eula=true" > /data/eula.txt
fi

# Run supervisor which maintains the minecraft server
/usr/bin/supervisord

